name: Documentation

on:
#   push:
#     branches:
#       - main
#     tags: 'v*'
#   pull_request:
#     branches:
#       - main
#     tags: 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Remove custom registry
        run: julia -e 'using Pkg; if "PKPackages" in keys(Pkg.Registry.reachable_registries()) Pkg.Registry.rm("PKPackages") end'
      - name: Add general registry
        run: julia -e 'using Pkg; Pkg.Registry.add("General")'
      - name: Check registries
        run: julia -e 'using Pkg; println("Registries:"); for reg in Pkg.Registry.reachable_registries() println("- ", reg.name, " (", reg.repo, ")") end'
      - name: Add custom registry
        run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "https://github.com/pavel-kalouguine/PKPackages.git"))'
      - name: Check registries
        run: julia -e 'using Pkg; println("Registries:"); for reg in Pkg.Registry.reachable_registries() println("- ", reg.name, " (", reg.repo, ")") end'
      - name: Instantiate docs environment
        run: julia --project=docs/ -e '
            using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs/ docs/make.jl